// <auto-generated />
using AdminPolizasAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminPolizasAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230610150204_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminPolizasAPI.Entidades.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Coberturas");
                });

            modelBuilder.Entity("AdminPolizasAPI.Entidades.Poliza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Polizas");
                });

            modelBuilder.Entity("AdminPolizasAPI.Entidades.PolizasCoberturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoberturaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoAsegurado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("PolizaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoberturaId");

                    b.HasIndex("PolizaId");

                    b.ToTable("PolizasCoberturas");
                });

            modelBuilder.Entity("AdminPolizasAPI.Entidades.PolizasCoberturas", b =>
                {
                    b.HasOne("AdminPolizasAPI.Entidades.Cobertura", "Cobertura")
                        .WithMany("PolizasCoberturas")
                        .HasForeignKey("CoberturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPolizasAPI.Entidades.Poliza", "Poliza")
                        .WithMany("PolizasCoberturas")
                        .HasForeignKey("PolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobertura");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("AdminPolizasAPI.Entidades.Cobertura", b =>
                {
                    b.Navigation("PolizasCoberturas");
                });

            modelBuilder.Entity("AdminPolizasAPI.Entidades.Poliza", b =>
                {
                    b.Navigation("PolizasCoberturas");
                });
#pragma warning restore 612, 618
        }
    }
}
